<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MobileDeviceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mobile_devices')->insert([
            [
                'device_name' => 'SamsungGalaxyS23Ultra',
                'score' => '1868',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => ' SamsungGalaxyS23Plus',
                'score' => '1858',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS23',
                'score' => '1841',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => ' VivoiQOO11Pro',
                'score' => '1767',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => ' VivoX90',
                'score' => '1750',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => ' VivoX90Pro+',
                'score' => '1742',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => ' OnePlus11',
                'score' => '1725',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK60Pro',
                'score' => '1724',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => ' Xiaomi13',
                'score' => '1723',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyZFold4',
                'score' => '1659',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'MotorolaEdgeX30',
                'score' => '1615',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LenovoLegionY90',
                'score' => '1612',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'NubiaRedMagic8Pro',
                'score' => '1603',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK50Ultra',
                'score' => '1538',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Xiaomi12SPro',
                'score' => '1499',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiBlackShark4Pro',
                'score' => '1475',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoiQOO10',
                'score' => '1472',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Xiaomi12SUltra',
                'score' => '1471',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperia1III',
                'score' => '1470',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'MicrosoftSurfaceDuo2',
                'score' => '1465',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaPRO-I',
                'score' => '1465',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LenovoLegion2Pro',
                'score' => '1465',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OPPOFindX5Pro',
                'score' => '1459',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyZFlip4',
                'score' => '1455',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoX80',
                'score' => '1409',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel7Pro',
                'score' => '1406',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus10T',
                'score' => '1385',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperia5III',
                'score' => '1370',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel6a',
                'score' => '1369',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK50Pro',
                'score' => '1364',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel6',
                'score' => '1359',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel7',
                'score' => '1345',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel6Pro',
                'score' => '1333',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus10Pro5G',
                'score' => '1306',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfone8Flip',
                'score' => '1296',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyZFold35G',
                'score' => '1282',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeGTNeo2',
                'score' => '1249',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiBlackShark4',
                'score' => '1247',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LenovoLegionPro',
                'score' => '1246',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus9R',
                'score' => '1242',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfone8',
                'score' => '1242',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusROGPhone5Pro',
                'score' => '1237',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus9R5G',
                'score' => '1229',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus9RT',
                'score' => '1215',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyTabS7+',
                'score' => '1202',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi11Ultra',
                'score' => '1201',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiBlackShark3',
                'score' => '1191',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate40Pro+',
                'score' => '1189',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyTabS7',
                'score' => '1185',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK40',
                'score' => '1184',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate40Pro',
                'score' => '1178',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'ASUSROGPhone3',
                'score' => '1177',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi11',
                'score' => '1174',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote205G',
                'score' => '1172',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP50Pro',
                'score' => '1165',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiBlackShark3Pro',
                'score' => '1163',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus8T+5G',
                'score' => '1161',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP50Pro+5G',
                'score' => '1160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyZFlip3',
                'score' => '1157',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus8T',
                'score' => '1155',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Xiaomi12TPro',
                'score' => '1154',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote20Ultra5G',
                'score' => '1150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus8',
                'score' => '1146',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperia5II',
                'score' => '1140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus8Pro',
                'score' => '1134',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyZFold25G',
                'score' => '1131',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperia1II',
                'score' => '1120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate40',
                'score' => '1120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusROGPhone5s',
                'score' => '1112',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusROGPhone5',
                'score' => '1111',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK50',
                'score' => '1107',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoF3',
                'score' => '1099',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusNord25G',
                'score' => '1096',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeGT5G',
                'score' => '1096',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote11TPro',
                'score' => '1095',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusROGPhone5Ultimate',
                'score' => '1093',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi11X',
                'score' => '1091',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeGTNeo3',
                'score' => '1090',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus10R',
                'score' => '1083',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Xiaomi11T',
                'score' => '1082',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Xiaomi11TPro',
                'score' => '1080',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoX4GT',
                'score' => '1076',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoF2Pro',
                'score' => '1074',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi10Ultra',
                'score' => '1074',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi10T5G',
                'score' => '1054',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi10TPro5G',
                'score' => '1047',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfone7',
                'score' => '1028',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusAce',
                'score' => '1018',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK40Gaming',
                'score' => '1009',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK50i',
                'score' => '1008',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'NothingPhone(1)',
                'score' => '998',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeGTNeo',
                'score' => '997',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote20Ultra',
                'score' => '991',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusNord2T',
                'score' => '990',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote205G',
                'score' => '988',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote20',
                'score' => '985',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeGTMaster',
                'score' => '980',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoiQOOPro5G',
                'score' => '977',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus7TPro5G',
                'score' => '976',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyTabS7FE',
                'score' => '972',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus7TPro',
                'score' => '967',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus7T',
                'score' => '965',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoX3Pro',
                'score' => '965',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi11Lite',
                'score' => '963',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeX7Pro',
                'score' => '961',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus7Pro5G',
                'score' => '957',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Xiaomi11Lite5GNE',
                'score' => '946',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonorV30Pro',
                'score' => '944',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA52S5G',
                'score' => '941',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus7Pro',
                'score' => '940',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OppoReno10xZoom',
                'score' => '940',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus7',
                'score' => '937',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate30Pro5G',
                'score' => '936',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperia5',
                'score' => '936',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperia1',
                'score' => '931',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyQuantum2',
                'score' => '930',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA73',
                'score' => '926',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP40',
                'score' => '923',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP40Pro',
                'score' => '921',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGV50SThinQ5G',
                'score' => '916',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGV50ThinQ5G',
                'score' => '908',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfone6ZS630KL',
                'score' => '906',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK20ProPremiumEdition',
                'score' => '906',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusROGPhoneII',
                'score' => '905',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA905G',
                'score' => '904',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate30Pro',
                'score' => '903',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyTabS6',
                'score' => '900',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK30Ultra',
                'score' => '899',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel4',
                'score' => '885',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusNordCE2',
                'score' => '885',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyFold5G',
                'score' => '884',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusNordN20',
                'score' => '884',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGG8SThinQ',
                'score' => '882',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyM52',
                'score' => '882',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusNordCE2Lite',
                'score' => '881',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeX3',
                'score' => '879',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGG8ThinQ',
                'score' => '878',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote10+5G',
                'score' => '875',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel4XL',
                'score' => '869',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote10',
                'score' => '867',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi9',
                'score' => '865',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi9TPro',
                'score' => '862',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeX2Pro',
                'score' => '858',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'ZTEnubiaRedMagic3',
                'score' => '856',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA535G',
                'score' => '855',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK20Pro',
                'score' => '851',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonorView20',
                'score' => '848',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA33',
                'score' => '837',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusNordCE5G',
                'score' => '828',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote105G',
                'score' => '827',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi10TLite5G',
                'score' => '827',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyTabS7FE5G',
                'score' => '827',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote10+',
                'score' => '821',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor20+',
                'score' => '819',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA515G',
                'score' => '818',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote10+5G',
                'score' => '811',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoX3GT',
                'score' => '801',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor20Pro',
                'score' => '800',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA715G',
                'score' => '800',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP30',
                'score' => '784',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusNord',
                'score' => '777',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusNordN105G',
                'score' => '777',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia8.35G',
                'score' => '777',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Huaweinova5T',
                'score' => '775',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel5',
                'score' => '773',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperia10III',
                'score' => '773',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperia10IIILite',
                'score' => '771',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor9X',
                'score' => '770',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate20Pro',
                'score' => '765',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiBlackShark2',
                'score' => '765',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA525G',
                'score' => '763',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP40Lite',
                'score' => '763',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel4a5G',
                'score' => '761',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiBlackShark2Pro',
                'score' => '757',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => ' HuaweiMate20X',
                'score' => '753',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate20',
                'score' => '745',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP30Pro',
                'score' => '744',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Realme75G',
                'score' => '744',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote9Pro',
                'score' => '728',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Realme7Pro',
                'score' => '728',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote9S',
                'score' => '726',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Realme6Pro',
                'score' => '726',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoM2Pro',
                'score' => '725',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoX3NFC',
                'score' => '718',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA225G',
                'score' => '716',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoX3',
                'score' => '709',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote10Pro',
                'score' => '701',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeX2',
                'score' => '699',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OppoReno2',
                'score' => '695',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA52',
                'score' => '684',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi9T',
                'score' => '682',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiNote10',
                'score' => '682',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote10Pro',
                'score' => '675',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA80',
                'score' => '674',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'NokiaX10',
                'score' => '671',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA72',
                'score' => '671',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'NokiaX20',
                'score' => '670',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusNordN2005G',
                'score' => '670',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote10',
                'score' => '665',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiK20',
                'score' => '662',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Realme6',
                'score' => '660',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyM51',
                'score' => '642',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA71',
                'score' => '639',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote10+',
                'score' => '638',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoV15Pro',
                'score' => '637',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Realme8',
                'score' => '633',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote7Pro',
                'score' => '631',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Realme7',
                'score' => '628',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoX2',
                'score' => '618',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyF62',
                'score' => '614',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusROGPhone',
                'score' => '612',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA70',
                'score' => '609',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfone5z',
                'score' => '550',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXZ2Compact',
                'score' => '548',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HTCU12+',
                'score' => '546',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXZ2Premium',
                'score' => '546',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXZ2',
                'score' => '544',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia9',
                'score' => '542',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXZ3',
                'score' => '541',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RazerPhone2',
                'score' => '538',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Meizu16th',
                'score' => '537',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote10Lite',
                'score' => '526',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus6',
                'score' => '524',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote9',
                'score' => '521',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus6T',
                'score' => '517',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGG7ThinQ',
                'score' => '511',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS9+',
                'score' => '510',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel3XL',
                'score' => '507',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGV35ThinQ',
                'score' => '507',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMix2S',
                'score' => '505',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS9',
                'score' => '503',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel3',
                'score' => '496',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi8',
                'score' => '495',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocophoneF1',
                'score' => '487',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGV40ThinQ',
                'score' => '469',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiMix3',
                'score' => ' 468',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoF1',
                'score' => ' 457',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OppoRenoZ',
                'score' => '454',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'device_name' => 'Realme5Pro',
                'score' => ' 445',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeXT',
                'score' => ' 444',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi9SE',
                'score' => '438',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiBlackShark',
                'score' => ' 437',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'device_name' => 'VivoZ1Pro',
                'score' => '436',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OppoReno',
                'score' => '428',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Realme3Pro',
                'score' => '427',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RealmeX',
                'score' => '427',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA32',
                'score' => '427',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia8.1',
                'score' => '417',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA41',
                'score' => '416',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HTCU11+',
                'score' => '415',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus5T',
                'score' => '412',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXZ1Compact',
                'score' => '411',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'RazerPhone',
                'score' => '410',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmi9',
                'score' => '408',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HTCU11',
                'score' => '407',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi9Lite',
                'score' => '407',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmi10X4G',
                'score' => '407',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoS1',
                'score' => '406',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi8SE',
                'score' => '403',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'EssentialPH-1',
                'score' => '402',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor8Pro',
                'score' => '402',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoS1',
                'score' => '402',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiNova2s',
                'score' => '402',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonorV9',
                'score' => '400',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote8',
                'score' => '399',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiMix2',
                'score' => '399',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXZ1',
                'score' => '399',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGV30',
                'score' => '398',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia8',
                'score' => '398',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP10Plus',
                'score' => '397',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor9',
                'score' => '397',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXZPremium',
                'score' => '396',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'MotorolaMotoZ2Force',
                'score' => '396',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP10',
                'score' => '395',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS8',
                'score' => '395',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'ZTENubiaZ17',
                'score' => '395',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS8+',
                'score' => '394',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMI6',
                'score' => '394',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate9',
                'score' => '391',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA31',
                'score' => '389',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel2',
                'score' => '383',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyTabS410.5',
                'score' => '380',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel2XL',
                'score' => '378',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA22',
                'score' => '370',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonorView10',
                'score' => '369',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel3aXL',
                'score' => '369',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP9',
                'score' => '368',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMediaPadM38.4',
                'score' => '366',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote8',
                'score' => '365',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyTabS5e',
                'score' => '365',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiMix',
                'score' => '364',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS8+',
                'score' => '363',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel3a+',
                'score' => '363',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate8',
                'score' => '362',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoXplay6',
                'score' => '362',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS8',
                'score' => '360',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate9Pro',
                'score' => '360',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor8',
                'score' => '359',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP9Plus',
                'score' => '356',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMI5s',
                'score' => '354',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoX20A',
                'score' => '354',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor8X',
                'score' => '354',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyTabS6Lite',
                'score' => '354',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OPPOR11',
                'score' => '353',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiPad4',
                'score' => '353',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA50',
                'score' => '352',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiA2',
                'score' => '351',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Qihoo360N6Pro',
                'score' => '350',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote7',
                'score' => '350',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia7Plus',
                'score' => '349',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiA2',
                'score' => '349',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia7.2',
                'score' => '349',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus3T',
                'score' => '348',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiNote3',
                'score' => '348',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Huaweinova3i',
                'score' => '348',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungTabS6Lite',
                'score' => '347',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMI5sPlus',
                'score' => '346',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi8Lite',
                'score' => '346',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS7',
                'score' => '345',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor9X',
                'score' => '345',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'MotorolaOneAction',
                'score' => '345',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiY9(2019)',
                'score' => '345',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiPSmartZ',
                'score' => '344',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor10Lite',
                'score' => '343',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiY9s',
                'score' => '341',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HTCUUltra',
                'score' => '340',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote7S',
                'score' => '340',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiY9Prime(2019)',
                'score' => '339',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor20lite',
                'score' => '339',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor8X',
                'score' => '338',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyM21',
                'score' => '337',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'MeizuPro7Plus',
                'score' => '337',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP30lite',
                'score' => '333',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixelXL',
                'score' => '332',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus3',
                'score' => '331',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmi9T',
                'score' => '331',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenpad3S10',
                'score' => '330',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LenovoZUKZ2',
                'score' => '329',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LeEcoLeMax2',
                'score' => '329',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor10',
                'score' => '329',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiA3',
                'score' => '329',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OppoF11Pro',
                'score' => '329',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiPocoM3',
                'score' => '329',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS8Active',
                'score' => '329',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGG5',
                'score' => '327',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA51',
                'score' => '327',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyM31s',
                'score' => '327',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia5.3',
                'score' => '326',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate20lite',
                'score' => '324',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote8T',
                'score' => '324',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyM31',
                'score' => '324',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia5.4',
                'score' => '324',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS7edge',
                'score' => '323',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixel',
                'score' => '323',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote8',
                'score' => '323',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA8(2018)',
                'score' => '321',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA9(2018)',
                'score' => '320',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperia10II',
                'score' => '320',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyF41',
                'score' => '320',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA50s',
                'score' => '319',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyM30s',
                'score' => '318',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Realme5',
                'score' => '318',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LenovoZUKZ2Pro',
                'score' => '318',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMi5',
                'score' => '318',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiNote2',
                'score' => '317',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA7',
                'score' => '316',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Realme3',
                'score' => '316',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OppoF9',
                'score' => '313',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfoneMaxPro(M2)',
                'score' => '312',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'ZTEAxon7',
                'score' => '312',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OppoF7',
                'score' => '311',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA8+(2018)',
                'score' => '310',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGV20',
                'score' => '309',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LGG6',
                'score' => '308',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'MeizuPRO6Plus',
                'score' => '308',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HTC10',
                'score' => '307',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OppoF9Pro',
                'score' => '302',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyTabS29.7(2016)',
                'score' => '300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OppoRealme1',
                'score' => '297',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfone5Max',
                'score' => '293',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiMax3',
                'score' => '292',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyTabS3',
                'score' => '291',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote5AI',
                'score' => '291',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'device_name' => 'MotorolaMotoG7',
                'score' => '291',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'device_name' => 'Nokia6.2',
                'score' => '291',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'device_name' => 'XiaomiRedmiNote5Pro',
                'score' => '290',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'device_name' => 'SonyXperia10Plus',
                'score' => '290',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote6Pro',
                'score' => '289',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmi7',
                'score' => '289',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia6.1Plus',
                'score' => '288',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfoneMaxPro(M1)',
                'score' => '287',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'MotorolaMotoG7Power',
                'score' => '286',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenFoneMaxPro(M1)',
                'score' => '285',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXZs',
                'score' => '284',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'MotorolaMotoZ',
                'score' => '283',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfone3Ultra',
                'score' => '281',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS7',
                'score' => '280',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia7.1',
                'score' => '278',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyM30',
                'score' => '275',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA40',
                'score' => '273',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyM20',
                'score' => '272',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA30s',
                'score' => '271',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'ZTENubiaZ17Mini',
                'score' => '270',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlusNordN100',
                'score' => '269',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenpadZ8',
                'score' => '269',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia3.4',
                'score' => '265',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote5',
                'score' => '263',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA30',
                'score' => '262',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'GooglePixelC',
                'score' => '261',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS7edge',
                'score' => '255',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS6edge',
                'score' => '255',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyS7edge+',
                'score' => '253',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiRedmiNote3',
                'score' => '251',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyNote5Duos',
                'score' => '240',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA9Pro',
                'score' => '232',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyC9Pro',
                'score' => '229',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'OnePlus2',
                'score' => '215',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiMate10Lite',
                'score' => '210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor7X',
                'score' => '210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP20Lite',
                'score' => '209',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiHonor9Lite',
                'score' => '209',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoV9',
                'score' => '208',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiP10Lite',
                'score' => '207',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA12s',
                'score' => '206',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LenovoYogabookYB1-X90F',
                'score' => '200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA21s',
                'score' => '200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperia8',
                'score' => '199',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyC7Pro',
                'score' => '199',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'HuaweiNova2i',
                'score' => '197',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'LenovoP2',
                'score' => '194',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'MotorolaMotoX4',
                'score' => '193',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'MotorolaMotoG6Plus',
                'score' => '193',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXA2Ultra',
                'score' => '192',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiA1',
                'score' => '191',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'XiaomiMiMax2',
                'score' => '191',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfone4',
                'score' => '191',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaAce',
                'score' => '191',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfone5',
                'score' => '191',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'AsusZenfone3',
                'score' => '190',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Nokia6.1',
                'score' => '189',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoX9',
                'score' => '188',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXA1Ultra',
                'score' => '186',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SonyXperiaXA1Plus',
                'score' => '184',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyC5Pro',
                'score' => '179',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA5(2017)',
                'score' => '166',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'VivoV7+',
                'score' => '164',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA20s',
                'score' => '153',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'SamsungGalaxyA12',
                'score' => '151',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
