<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Speciality;
use Illuminate\Support\Facades\DB;

class SpecialitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Speciality::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        $data = [
            [
                "id" => 1,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Acupuncture",
                "slug" => "acupuncture",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 2,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Allergy Specialist",
                "slug" => "allergy-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 3,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Andrologist",
                "slug" => "andrologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 4,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Anesthetist",
                "slug" => "anesthetist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 5,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Audiologist",
                "slug" => "audiologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 6,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Cancer Specialist / Oncologist",
                "slug" => "cancer-specialist-oncologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 7,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Chest Respiratory Specialist",
                "slug" => "chest-respiratory-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 8,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Chest Surgeon",
                "slug" => "chest-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 9,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Endourologist",
                "slug" => "endourologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 10,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "ENT Specialist",
                "slug" => "ent-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 11,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "ENT Surgeon",
                "slug" => "ent-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 12,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Gastroenterologist",
                "slug" => "gastroenterologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 13,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "General Physician",
                "slug" => "general-physician",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 14,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Hematologist",
                "slug" => "hematologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 15,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Homeopath",
                "slug" => "homeopath",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 16,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Laparoscopic Surgeon",
                "slug" => "laparoscopic-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 17,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Liver Specialist",
                "slug" => "liver-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 18,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Liver Transplant Surgeon",
                "slug" => "liver-transplant-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 19,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Medical Specialist",
                "slug" => "medical-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 20,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Neonatologist",
                "slug" => "neonatologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 21,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Neuro Psychiatrist",
                "slug" => "neuro-psychiatrist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 22,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Neurologist",
                "slug" => "neurologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 23,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Oral and Maxillofacial Surgeon",
                "slug" => "oral-and-maxillofacial-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 24,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Orthodontist",
                "slug" => "orthodontist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 25,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Pediatric Nephrologist",
                "slug" => "pediatric-nephrologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 26,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Pediatrician",
                "slug" => "pediatrician",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 27,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Physiotherapist",
                "slug" => "physiotherapist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 28,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Psychiatrist",
                "slug" => "psychiatrist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 29,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Psychologist",
                "slug" => "psychologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 30,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Radiologist",
                "slug" => "radiologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 31,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Rehabilitation Medicine",
                "slug" => "rehabilitation-medicine",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 32,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Rheumatologist",
                "slug" => "rheumatologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 33,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Speech Therapist",
                "slug" => "speech-therapist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => 1,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 34,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Gynecologist",
                "slug" => "gynecologist",
                "image" => "gynecologist.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 35,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Dentist",
                "slug" => "dentist",
                "image" => "dentist.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 36,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Eye Specialist",
                "slug" => "eye-specialist",
                "image" => "eye-specialist.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 37,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "General Surgeon",
                "slug" => "general-surgeon",
                "image" => "general-surgeon.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 38,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Obstetrician",
                "slug" => "obstetrician",
                "image" => "obstetrician.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 39,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Orthopedic Surgeon",
                "slug" => "orthopedic-surgeon",
                "image" => "orthopedic-surgeon.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 40,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Cardiologist",
                "slug" => "cardiologist",
                "image" => "cardiologist.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 41,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Cosmetologist",
                "slug" => "cosmetologist",
                "image" => "cosmetologist.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 42,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Internal Medicine Specialist",
                "slug" => "internal-medicine-specialist",
                "image" => "internal-medicine-specialist.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 43,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Diabetologist",
                "slug" => "diabetologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 44,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Eye Surgeon",
                "slug" => "eye-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 45,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Nutritionist",
                "slug" => "nutritionist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 46,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Urologist",
                "slug" => "urologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 47,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Cardiac Surgeon",
                "slug" => "cardiac-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 48,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Cardiothoracic Surgeon",
                "slug" => "cardiothoracic-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 49,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Child-Kidney Specialist",
                "slug" => "child-kidney-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 50,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Chiropractor",
                "slug" => "chiropractor",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 51,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Cosmetic Dentist",
                "slug" => "cosmetic-dentist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 52,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Cosmetic Surgeon",
                "slug" => "cosmetic-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 53,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Diabetes Counsellor",
                "slug" => "diabetes-counsellor",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 54,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Dietitian",
                "slug" => "dietitian",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 55,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Endocrinologist",
                "slug" => "endocrinologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 56,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Endodontist",
                "slug" => "endodontist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 57,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Fertility Consultant",
                "slug" => "fertility-consultant",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 58,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Head and Neck Surgeon",
                "slug" => "head-and-neck-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 59,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Hepatologist",
                "slug" => "hepatologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 60,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Hypertension Specialist",
                "slug" => "hypertension-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 61,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Immunologist",
                "slug" => "immunologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 62,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Implantologist",
                "slug" => "implantologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 63,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Interventional Cardiologist",
                "slug" => "interventional-cardiologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 64,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Laser Specialist",
                "slug" => "laser-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 65,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Male Sexual Health Specialist",
                "slug" => "male-sexual-health-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 66,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Nephrologist",
                "slug" => "nephrologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 67,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Neurosurgeon",
                "slug" => "neurosurgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 68,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Oncologist",
                "slug" => "oncologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 69,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Pain Management Specialist",
                "slug" => "pain-management-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 70,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Pediatric Cardiologist",
                "slug" => "pediatric-cardiologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 71,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Pediatric Nutritionist",
                "slug" => "pediatric-nutritionist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 72,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Pediatric Orthopedic Surgeon",
                "slug" => "Pediatric-Orthopedic-Surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 73,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Pediatric Surgeon",
                "slug" => "Pediatric-Surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 74,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Plastic Surgeon",
                "slug" => "Plastic-Surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 75,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Prosthodontist",
                "slug" => "Prosthodontist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 76,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Pulmonologist",
                "slug" => "pulmonologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 77,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Rehablitation Specialist",
                "slug" => "rehablitation-specialist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 78,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Restorative Dentist",
                "slug" => "restorative-dentist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 79,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Sexologist",
                "slug" => "sexologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 80,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Sleep Medicine Doctor",
                "slug" => "sleep-medicine-doctor",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 81,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Sonologist",
                "slug" => "sonologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 82,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Speech and Language Pathologist",
                "slug" => "speech-and-language-pathologist",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 83,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Spinal Surgeon",
                "slug" => "spinal-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 84,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Thyroid Surgeon",
                "slug" => "thyroid-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                "id" => 85,
                "translation_of" => null,
                "lang_id" => 1,
                "name" => "Vascular Surgeon",
                "slug" => "vascular-surgeon",
                "image" => "image.png",
                "status" => 1,
                "action_by" => null,
                "created_at" => now(),
                "updated_at" => now()
            ]
        ];
        Speciality::insert($data);
    }
}
